/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
    import flash.display.Sprite;
    
    import sk.yoz.ycanvas.map.demo.utils.BingMapsUtilsTest;
    
    public class FlexUnitCompilerApplication extends Sprite
    {
        
        private var sk_yoz_ycanvas_map_demo_utils_BingMapsUtilsTest_obj:sk.yoz.ycanvas.map.demo.utils.BingMapsUtilsTest;
    }
}